### ISSUE TITLE
Set org level LUAROCKS_APIKEY secret

### ISSUE THREAD

**Issue by alerque** [lunarmodules/.github#3]
Per [this team discussion](https://github.com/orgs/lunarmodules/teams/admins/discussions/2?from_comment=4#discussion-2-comment-4) I still don't have org level access to set this.

@daurnimator here is a current key that can be set as `LUAROCKS_APIKEY` in the org for use by child repos, encrypted to your GPG key.

**Encrypted message removed**

**Comment by daurnimator** [comment]
Added.
